version: '3.1'
services:
  mongo:
    image: mongo
    restart: always
    expose:
      - 27017
      - 27018
      - 27019
    ports:
      - 27017:27017
      - 27018:27018
      - 27019:27019
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: always
    expose:
      - '8081'
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
  backend:
    image: 'node:8'
    user: 'node'
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend:/home/node/app
    expose:
      - '4455'
    ports:
      - 4455:4455
    command: bash -c 'npm i && npm start'
    environment:
        SERVER_PORT: 4455
  frontend:
    image: 'node:8'
    user: 'node'
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./frontend/phone-book:/home/node/app
    expose:
      - '8080'
    ports:
      - 8080:8080
    command: bash -c 'npm i && npm build --prod && npm run serve'
    environment:
        SERVER_PORT: 4455
